apiVersion: v1
kind: Service
metadata:
  name: pyredidem-service
spec:
  selector:
    app: pyredidem
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # Use ClusterIP if you want to access Redis internally within the cluster
